#!/bin/sh /etc/rc.common

USE_PROCD=1
START=96
STOP=04

start_service() {
	procd_open_instance supervisor
	procd_set_param command /usr/libexec/opl-netfleet/supervisor.uc
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_close_instance
}
