import * as fs from "fs";
import { cursor } from "uci";
import { get, profile_get, profile_save, profile_delete, backup_export, backup_restore, core_action, diagnostics } from "/usr/libexec/opl-netfleet/application/maintenance.uc";
import { sha256, current_profile, shell_quote as q } from "/usr/libexec/opl-netfleet/adapters/uci.uc";

function check(value, label) { if (!value) die(label); };
const work = "/tmp/netfleet-maintenance-fixture";
const envelope = `${work}/request.json`;
const lock = fs.open("/var/lock/opl-netfleet-deploy.lock", "a", 0600);
check(lock != null && lock.lock("xn"), "maintenance fixture owns global lock");
function invoke(fn, value) {
	check(fs.writefile(envelope, sprintf("%J", { request: { revision: get().result.revision, ...value } })) > 0 && fs.chmod(envelope, 0600), "private request written");
	return fn(envelope);
};
function cloned(value) { return json(sprintf("%J", value)); };
function report(result, label) { check(result.ok, `${label}: ${result.error ?? "unknown"}`); };
const before = get();
check(before.ok && before.result.supported, "native maintenance is available");
const baseline_revision = before.result.revision;
const baseline_profile = current_profile();
if (ARGV[0] == "stopped") {
	check(before.result.core.running == false, "stopped fixture precondition");
	const exported = backup_export();
	report(exported, "stopped export");
	report(invoke(backup_restore, { backup: exported.result.backup, confirm: true }), "stopped restore");
	check(get().result.core.running == false && current_profile() == baseline_profile, "stopped restore does not start core");
	check(diagnostics().result.controller_available == false, "diagnostics works without controller");
	lock.close();
	print("maintenance_stopped_ok\n");
	exit(0);
}
check(before.result.core.running, "running fixture precondition");
const packaged_baseline = "/etc/opl-netfleet/policy-sources/base-v1.json";
const baseline_mode = fs.stat(packaged_baseline)?.mode & 0777;
check(fs.chmod(packaged_baseline, 0644), "packaged public baseline mode");
const profile = { proxies: [], "proxy-groups": [], rules: ["MATCH,DIRECT"] };
report(invoke(profile_save, { id: "maintenance-fixture.json", content: sprintf("%J", profile) }), "JSON import");
const downloaded = profile_get("maintenance-fixture.json");
check(downloaded.ok && json(downloaded.result.profile.content).rules[0] == "MATCH,DIRECT", "authenticated JSON export");
report(invoke(profile_save, { id: "maintenance-fixture.yaml", content: "proxies: []\nproxy-groups: []\nrules:\n  - MATCH,DIRECT\n" }), "YAML import");
check(profile_get("maintenance-fixture.yaml").result.profile.format == "yaml", "YAML format retained");
const upload_id = "4ca91a4f0f354e898aac5273279ea20f";
const upload = `/tmp/opl-netfleet-upload.${upload_id}.json`;
check(fs.writefile(upload, sprintf("%J", { request: { revision: get().result.revision, id: "maintenance-fixture.json", content: sprintf("%J", profile) } })) > 0 && fs.chmod(upload, 0600), "private upload staged");
check(fs.writefile(envelope, sprintf("%J", { request: { upload_id: upload_id } })) > 0, "upload pointer staged");
report(profile_save(envelope), "uploaded profile import");
check(fs.lstat(upload) == null, "private upload consumed and deleted");
check(!invoke(profile_save, { upload_id: "../escape" }).ok, "upload IDs cannot carry paths");
check(!invoke(profile_save, { id: "../bad.json", content: "{}" }).ok, "traversal import rejected");
check(!invoke(profile_save, { revision: baseline_revision, id: "maintenance-fixture.json", content: "{}" }).ok, "stale profile edit rejected");
check(!invoke(profile_save, { id: "maintenance-fixture.json", content: "{bad" }).ok, "invalid config rejected");
const uci = cursor();
uci.set("netfleet", "mixin", "maintenance_preserve_test", "private-option");
check(uci.commit("netfleet") && fs.chmod("/etc/config/netfleet", 0600), "fixture private extra field");
const exported = backup_export();
report(exported, "backup export");
const archive = exported.result.backup;
check(length(filter(archive.files, file => file.path == "policy-sources/base-v1.json")) == 1, "0644 packaged baseline is backed up");
check(index(sprintf("%J", archive), "private-option") >= 0, "unexposed UCI fields exported");
check(length(filter(archive.files, file => file.path == "native/run/config.yaml" || index(file.path, "ownership") >= 0)) == 0, "backup excludes runtime ownership");
const digest = sha256("/etc/config/netfleet");
let unsafe = cloned(archive);
unsafe.files[0].path = "../../etc/shadow";
check(!invoke(backup_restore, { backup: unsafe, confirm: true }).ok && sha256("/etc/config/netfleet") == digest, "invalid backup rejected before mutation");
report(invoke(backup_restore, { backup: archive, confirm: true }), "active backup round trip");
check(current_profile() == baseline_profile && get().result.core.running, "active profile and core preserved");
check(cursor().get("netfleet", "mixin", "maintenance_preserve_test") == "private-option", "unexposed UCI field retained");

// This accepted JSON fails the selected gateway, after staging but before a successful activation.
const failing = cloned(archive);
failing.files = filter(failing.files, file => file.path != "native/mixin.json");
const old_mixin = filter(archive.files, file => file.path == "native/mixin.json")[0];
const mixin = old_mixin == null ? {} : json(b64dec(old_mixin.content));
mixin.listeners = [{ name: "maintenance-invalid-tun", type: "tun" }];
push(failing.files, { path: "native/mixin.json", encoding: "base64", content: b64enc(sprintf("%J", mixin)) });
const failed = invoke(backup_restore, { backup: failing, confirm: true });
check(!failed.ok && failed.result?.rollback?.ok == true, `failed activation restores inputs: ${failed.error}`);
check(get().result.core.running && current_profile() == baseline_profile, "failed restore recovers prior owner");
report(invoke(core_action, { action: "reload", confirm: true }), "core reload");
report(invoke(core_action, { action: "restart", confirm: true }), "core restart");
check(current_profile() == baseline_profile, "core maintenance preserves profile selection");
check(!invoke(core_action, { action: "stop", confirm: true }).ok, "unsupported service action rejected");
check(system(`logger -t opl-netfleet-core ${q("maintenance-fixture token=private-fixture https://example.test/?secret=private-fixture")}`) == 0, "diagnostic fixture logged");
const logs = diagnostics();
check(logs.ok && logs.result.supported && index(sprintf("%J", logs.result.lines), "private-fixture") < 0, "logs are bounded and redacted");
report(invoke(profile_delete, { id: "maintenance-fixture.json" }), "delete unused JSON profile");
report(invoke(profile_delete, { id: "maintenance-fixture.yaml" }), "delete unused YAML profile");
const cleanup = cursor();
cleanup.delete("netfleet", "mixin", "maintenance_preserve_test");
check(cleanup.commit("netfleet") && fs.chmod("/etc/config/netfleet", 0600), "fixture field removed");
check(fs.chmod(packaged_baseline, baseline_mode), "baseline mode restored");
fs.unlink(envelope);
lock.close();
print("maintenance_device_ok\n");
