const labels: Record<string, string> = {
  extension_component_not_installed: '未安装可选模块',
  extension_api_incompatible: '模块接口与当前 NetFleet 不兼容',
  extension_dependency_missing: '模块运行依赖缺失',
  extension_manifest_missing: '模块接口声明缺失',
  extension_manifest_invalid: '模块接口声明无效',
  extension_backend_unsupported: '当前后端不支持此模块',
  extension_owner_unavailable: '模块状态暂不可读取',
  extension_package_unknown: '模块安装版本尚未确认',
  dashboard_managed_externally: '面板由 Nikki 管理',
  dashboard_path_unmanaged: '当前面板目录未由 NetFleet 管理',
  dashboard_unpacker_unavailable: '缺少面板解压组件，请安装 unzip',
  dashboard_state_unavailable: '无法读取或保存面板更新记录',
  dashboard_release_check_failed: '无法检查面板发行源，请检查设备联网后重试',
  dashboard_candidate_changed: '面板候选版本已变化，请重新检查更新',
  dashboard_stage_unavailable: '无法准备面板更新目录，未开始替换',
  dashboard_download_failed: '面板下载失败，当前资源未替换',
  dashboard_asset_mismatch: '面板下载内容未通过校验，当前资源未替换',
  dashboard_archive_invalid: '面板压缩包无效，当前资源未替换',
  dashboard_insufficient_space: '面板更新空间不足，当前资源未替换',
  dashboard_unpack_failed: '面板解压失败，当前资源未替换',
  dashboard_replace_failed: '面板资源替换失败',
  dashboard_readback_failed: '更新后的面板访问检查失败',
  dashboard_recovery_failed: '面板资源恢复未确认，请检查当前面板',
  dashboard_update_failed: '面板更新未完成，请重新读取状态',
  feed_check_failed: '更新源检查失败，当前安装版本不变',
  feed_not_configured: '尚未配置签名更新源',
  core_managed_externally: '核心由其他后端或系统软件包管理',
  package_not_installed: '未安装受管理的软件包',
  package_manager_unavailable: '设备软件包管理器不可用',
  candidate_changed: '候选版本已变化，请重新检查更新',
  candidate_download_failed: '新版签名包下载或校验失败，当前版本不变',
  rollback_package_unavailable: '无法取得旧版签名回退包，未开始更新，仍保持原版',
  dependency_resolution_failed: '无法确认依赖关系，未开始安装',
  dependency_change_requires_system_manager: '此次更新需要调整系统依赖，请使用 OpenWrt 软件包管理器',
  package_validation_failed: '安装预检失败，当前版本不变',
  insufficient_update_space: '存储或临时空间不足，未开始更新，仍保持原版',
  core_config_incompatible: '新核心无法通过当前配置校验，未开始更新',
  runtime_precondition_failed: '当前运行状态未通过检查，未开始更新',
  runtime_readback_failed: '无法读取当前运行状态，未开始更新',
  runtime_stop_failed: '未能确认服务已安全停止，请检查当前运行状态',
  package_install_failed: '软件包安装失败',
  package_identity_mismatch: '安装后的版本与目标不一致',
  runtime_verification_failed: '更新后的运行检查失败',
  rollback_stop_failed: '恢复前无法确认服务已停止，请检查当前运行状态',
  rollback_install_failed: '旧版软件包恢复失败，请检查当前运行状态',
  rollback_identity_mismatch: '恢复后的版本尚未确认',
  rollback_runtime_failed: '旧版已恢复，但运行状态未通过检查',
  component_operation_failed: '组件操作未完成，请检查设备状态',
  previous_update_incomplete: '上次更新尚未完整恢复，请先确认当前版本和运行状态',
  private_configuration_changed: '更新期间设备配置发生变化',
  rollback_configuration_failed: '未能恢复更新前配置，请检查当前网络与配置',
  operation_interrupted: '设备操作已中断，执行结果尚未确认',
  invalid_component_request: '更新请求无效，请重新检查版本',
  unsafe_update_directory: '更新目录无法安全使用，未开始更新',
  update_identity_unavailable: '设备未能创建更新任务',
  update_stage_failed: '无法准备更新文件，未开始更新',
  update_state_write_failed: '无法保存更新状态',
  update_start_failed: '设备未能启动更新任务',
  update_request_changed: '更新条件已变化，请重新检查更新',
};

export function componentError(code: string): string {
  return code.endsWith('_rolled_back') ? `${componentError(code.slice(0, -12))}；已恢复更新前版本和运行状态` : labels[code] || code;
}
